export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';


export const SET_TODOS = 'SET_TODOS';
export const ADD_TODO = 'ADD_TODO';
export const TODO_FETCHED = 'TODO_FETCHED';
export const TODO_UPDATED = 'ODO_UPDATED';
export const TODO_DELETED = 'TODO_DELETED';
export const SET_CURRENT_USERTOKEN = 'SET_CURRENT_USERTOKEN';

